spring:
  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: true
eureka:
  client:
    enabled: false

#ap4k:
#  kubernetes:
#    envVars:
#      - name: SPRING_PROFILES_ACTIVE:
#        value: choas-monkey,docker,kubernetes
#    serviceType: NodePort
#    imagePullPolicy: Always
#    group: spencergibb